### ISSUE TITLE
macOS: Anna failed to build

### ISSUE THREAD

**Issue by kavirajk** [hydro-project/anna#1]
Tried to build anna locally as per docs. 

Steps:
1. Clone hydro-project/anna
2. Clone hydro-project/common -> hydro-project/anna/common
3. `./common/scripts/install-dependencies-osx.sh`
4. `./scripts/build.sh`

```
-bash-5.0$ ./scripts/build.sh
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
CMake Error at /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindProtobuf.cmake:599 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:70 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/Users/kaviraj/src/github.com/hydro-project/anna/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by mvu-tk** [comment]
I had the same issue building Anna.
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:56 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source "common/vendor/spdlog" which is not an
  existing directory.


CMake Error at CMakeLists.txt:57 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source "common/vendor/yamlcpp" which is not an
  existing directory.


CMake Error at CMakeLists.txt:58 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source "common/vendor/zeromq" which is not an
  existing directory.


CMake Error at CMakeLists.txt:59 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source "common/vendor/zeromqcpp" which is not an
  existing directory.


-- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.5.1") 
-- Configuring incomplete, errors occurred!
See also "../anna/build/CMakeFiles/CMakeOutput.log".


Here's the last line of CMakeOutput.log:
Run Build Command(s):/usr/local/bin/gmake cmTC_a1b51/fast && /usr/local/bin/gmake -f CMakeFiles/cmTC_a1b51.dir/build.make CMakeFiles/cmTC_a1b51.dir/build
gmake[1]: Entering directory '/Users/lap00584/ws/anna/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a1b51.dir/src.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_a1b51.dir/src.c.o   -c /Users/lap00584/ws/anna/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_a1b51
/usr/local/Cellar/cmake/3.15.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a1b51.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_a1b51.dir/src.c.o  -o cmTC_a1b51 
gmake[1]: Leaving directory '/Users/lap00584/ws/anna/build/CMakeFiles/CMakeTmp'


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

**Comment by vsreekanti** [comment]
Hi @mvu-tk, what command did you run that generated the above output?

**Comment by mvu-tk** [comment]
first I ran common/scripts/install-dependencies-osx.sh, then I run anna/scripts/build.sh
I use macOS Mojave 10.14.6

regards,
-M

**Comment by vsreekanti** [comment]
@mvu-tk, it looks like you didn't successfully clone the `common` submodule. Did you include the `--recurse-submodules` flag when you cloned the repo?
