### ISSUE TITLE
anna under k8s

### ISSUE THREAD

**Issue by mvu-tk** [hydro-project/anna#14]
would it be a good idea to run anna under container and k8s where each instance can come and go at any time?
thank you for reading this.

regards,
-M

**Comment by vsreekanti** [comment]
Hi @mvu-tk, this capability already exists. You can find a getting started guide [here](https://github.com/hydro-project/cluster/blob/master/docs/getting-started-aws.md) and the Docker images [here](https://hub.docker.com/orgs/hydroproject).

**Comment by mvu-tk** [comment]
thank you very much!
