### ISSUE TITLE
Does Anna supports G-Counter (Grow-only Counter)?

### ISSUE THREAD

**Issue by authwork** [hydro-project/anna#24]
Hello!
In Anna, it supports Last-Write-Wins Lattice.
Does Anna or Lattice support other CRDTs, e.g., Grow-only Counter? Are there any examples?
Many thanks in advance!

**Comment by vsreekanti** [comment]
Hi @authwork, you can see the full set of lattices we have implemented [here](https://github.com/hydro-project/common/tree/master/include/lattices). You can model a grow-only counter as the size of a `SetLattice` where you insert a unique element into the set every time you want to increment the counter.

**Comment by authwork** [comment]
Hi @vsreekanti 
Many thanks! That's a good idea.
In a more general case, e.g., adding a float point number to the old value of a key, it seems we cannot use the size (interge) to implement it.
An example:
PUT k 1.0
ADD k -2.1
ADD k 3.2
Then:
GET k = 1.0 + (-2.1) + (3.2) = 2.1

**Comment by vsreekanti** [comment]
@authwork, maybe I'm misunderstanding your use case, but it seems like this could be a set-based operation as well. On retrieval, instead of returning the length of the set as the count, you return the sum of the elements in the set as you do in the last line of your example. Does that make sense?

**Comment by authwork** [comment]
@vsreekanti 
I am not very sure about SetLattice. 
Then, I think it may cause two issues by returning the sum of the elements in the set:
1. With increasing ADD operations~(meaning O(n) elements in a Set), each GET will cause much overhead~(sum of O(n) elements)
2. the same elements cannot appear once again in a Set, then:
PUT k 1.0
ADD k -2.1
ADD k -2.1
ADD k 3.2
will be
GET k = 1.0 + (-2.1) + (3.2) = 2.1, (only one -2.1 in a set)
but we want 
GET k = 1.0 + (-2.1) + (-2.1) + (3.2) = 0

**Comment by vsreekanti** [comment]
@authwork -- those are good points about serialization costs. If this is a use case you'd like to support, we'd welcome a new lattice type contribution from you. We've generally been treating data as byte streams (hence the usage of `string`), but you can see other lattice definitions in the link I shared above.

**Comment by authwork** [comment]
Thanks.
I have figured out another solution before creating a new Lattice type.
This solution is I can first sum up the result at another server handler and then PUT it directly to the anna server.
I will compare their performance after I try them both.

**Comment by authwork** [comment]
@vsreekanti 
Hello, I have encounter another issue when using Anna:
```
anna/build/libanna-proto.a(anna.pb.cc.o): relocation R_X86_64_PC32 against symbol `_KeyTuple_default_instance_' can not be used when making a shared object; recompile with -fPIC
```
How can I recompile Anna with -fPIC?
I add  -fPIC in the CMakefile but do not work:
```
IF(${CMAKE_CXX_COMPILER} STREQUAL "/usr/bin/g++")
  SET(CMAKE_CXX_FLAGS_COMMON
          "-std=c++11 -pthread -fPIC")
ENDIF()

SET(CMAKE_CXX_FLAGS_DEBUG
    "${CMAKE_CXX_FLAGS_DEBUG} \
    ${CMAKE_CXX_FLAGS_COMMON} \
    -g -O0 -fprofile-arcs -ftest-coverage")

SET(CMAKE_CXX_FLAGS_RELEASE
    "${CMAKE_CXX_FLAGS_RELEASE} \
    ${CMAKE_CXX_FLAGS_COMMON} \
    -O3")
```

**Comment by authwork** [comment]
@vsreekanti 
It (the "-fPIC" issue) can be solved via manually modifiy the file build/CMakeFiles/anna-proto.dir/flags.make and insert "-fPIC". How to generate it with "-fPIC" automatically?

Then, it comes another issue about using GPU (nvcc)
```
[ 14%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_exp_layer.cu.o
[ 14%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_filter_layer.cu.o

anna/common/include/lattices/core_lattices.hpp(164): error: the object has type qualifiers that are not compatible with the member function "MapLattice<K, V>::at"
            object type is: const MapLattice<K, V>

1 error detected in the compilation of "/tmp/tmpxft_0000502a_00000000-4_cudnn_conv_layer.cpp4.ii".
CMake Error at cuda_compile_1_generated_cudnn_conv_layer.cu.o.Release.cmake:275 (message):
  Error generating file
CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_cudnn_conv_layer.cu.o

make[2]: *** Waiting for unfinished jobs....
```
