### ISSUE TITLE
Replication mechanism in Anna

### ISSUE THREAD

**Issue by authwork** [hydro-project/anna#25]
I have some questions about the replication mechanism in Anna:  
1. Is there any document talking about how to sync all replicas of a key-value pair? or the workflow of how anna receivers a user PUT request and distributed it to all replicas (N replicas) and how anna receivers a user PUT request and distributed it to 1/K replicas out of all replicas (N replicas)?
2. How to disabled Anna’s elasticity mechanism? Can I just not start anna-monitor?

**Comment by vsreekanti** [comment]
1. Currently, the easiest way to sync all replicas is to use the `get_all` client [method](https://github.com/hydro-project/anna/blob/master/client/python/anna/client.py#L118), which retrieves data from all replicas and merges them. In general, requests are routed to an individual KVS node. We use a background gossip/multicast protocol to asynchronously send updates from the receiving replica to all the other replicas on the hash ring responsible for the key. You can find a more detailed description of the protocol in the original [Anna paper](http://db.cs.berkeley.edu/jmh/papers/anna_ieee18.pdf).
2. You can disable the various scaling mechanisms in the Anna [config](https://github.com/hydro-project/anna/blob/master/conf/anna-base.yml#L15-L18).

**Comment by authwork** [comment]
Many thanks for you help!

**Comment by authwork** [comment]
Hello! @vsreekanti 
After reading ```get_all``` client method, I have one questions.
Given a set k = {v1, v2, v3, v4} and it has three replications R1(k) = {v1, v2, v3, v4}, R2(k) = {v1, v2, v3, v4}, R3(k) = {v1, v2, v3, v4}.
I execute two command:
Delete v4
Add v5
and we know the correct consistent answer is k = {v1, v2, v3, v5}.
However, because of the EC, R1(k) = {v1, v2, v3}, R2(k) = {v1, v2, v3, v5}, and R3(k) = {v1, v2, v3, v4}.
Using ```get_all``` client method will read R1(k), R2(k), and R3(k), then merge their values (Union):
```
void do_merge(const set<T> &e) {
    for (const T &elem : e) {
      this->element.insert(elem);
    }
  }
```
So, the answer is {v1, v2, v3, v4, v5}, which is not the correct consistent answer.
