### ISSUE TITLE
Compile issue when using Anna 

### ISSUE THREAD

**Issue by authwork** [hydro-project/anna#26]
Hello, I have encountered an issue when using Anna (Sorry for my careless of closing the old issue #24 ):
```
anna/build/libanna-proto.a(anna.pb.cc.o): relocation R_X86_64_PC32 against symbol `_KeyTuple_default_instance_' can not be used when making a shared object; recompile with -fPIC
```
How can I recompile Anna libs with -fPIC?
I add  -fPIC in the CMakefile but do not work:
```
IF(${CMAKE_CXX_COMPILER} STREQUAL "/usr/bin/g++")
  SET(CMAKE_CXX_FLAGS_COMMON
          "-std=c++11 -pthread -fPIC")
ENDIF()

SET(CMAKE_CXX_FLAGS_DEBUG
    "${CMAKE_CXX_FLAGS_DEBUG} \
    ${CMAKE_CXX_FLAGS_COMMON} \
    -g -O0 -fprofile-arcs -ftest-coverage")

SET(CMAKE_CXX_FLAGS_RELEASE
    "${CMAKE_CXX_FLAGS_RELEASE} \
    ${CMAKE_CXX_FLAGS_COMMON} \
    -O3")
```
Update:
It (the "-fPIC" issue) can be solved via manually modifying the file build/CMakeFiles/anna-proto.dir/flags.make and insert "-fPIC". How to generate it (via "Unix Makefiles" Generator, CMake Version 3.14) with "-fPIC" automatically?

Update: adding flags to CMAKE_CXX_FLAGS solves the issue.
```
IF(${CMAKE_CXX_COMPILER} STREQUAL "/usr/bin/g++")
  SET(CMAKE_CXX_FLAGS_COMMON
          "-fPIC -std=c++11 -pthread")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_COMMON}")
ENDIF()
```

2>
Then, it comes another issue about using GPU (nvcc)
```
[ 14%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_exp_layer.cu.o
[ 14%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_filter_layer.cu.o

anna/common/include/lattices/core_lattices.hpp(164): error: the object has type qualifiers that are not compatible with the member function "MapLattice<K, V>::at"
            object type is: const MapLattice<K, V>

1 error detected in the compilation of "/tmp/tmpxft_0000502a_00000000-4_cudnn_conv_layer.cpp4.ii".
CMake Error at cuda_compile_1_generated_cudnn_conv_layer.cu.o.Release.cmake:275 (message):
  Error generating file
CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_cudnn_conv_layer.cu.o

make[2]: *** Waiting for unfinished jobs....
```

**Comment by vsreekanti** [comment]
You should not need to use `-fPIC`. What version of `libprotobuf` do you have installed?

**Comment by authwork** [comment]
Oh, it is right when I complie Anna itself.
But when I use Anna's libs in other projects, I uses ```ld``` to link libanna-proto.a and this error happens.  The solution is to recomplie libanna-proto.a with flag ```-fPIC```. (set it into CMAKE_CXX_FLAGS).

**Comment by authwork** [comment]
Update: the GPU issus is solved.
The issue is [The object has type qualifiers that are not compatible with the member function C++](https://stackoverflow.com/questions/38780754/the-object-has-type-qualifiers-that-are-not-compatible-with-the-member-function).
It is caused by calling non-const member function on a const object.

anna/common/include/lattices/core_lattices.hpp
```
V &at(K k) const { return this->element[k]; } // add const here
```
in CMakefile.txt, we add ```-fpermissive``` into CMAKE_CXX_FLAGS.
This will remove the issue.

**Comment by vsreekanti** [comment]
Got it. Thanks @authwork. Do you think it is worth adding this flag to the standard compile toolchain?

**Comment by authwork** [comment]
It only provide the solution for some rare cases, e.g., our project under nvcc. 
```-fpermissive```, in fact, turns some "Errors" to "Warns".
We can add a ```nvcc``` label on this issue.
