### ISSUE TITLE
Anna performance

### ISSUE THREAD

**Issue by catherine917** [hydro-project/anna#28]
Hello, I know Anna offers world-beating speed at many scales. To get down the details, I wanted to benchmark anna against Redis with YCSB. But I didn't find Anna's adapter in YCSB. Therefore, I was wondering how to connect to Anna using YCSB? Is there any documentation or package about it?

Best Regards

**Comment by vsreekanti** [comment]
Hi @catherine917 -- thanks for your question. Our YCSB-style workload generator can be found [here](https://github.com/hydro-project/anna/blob/master/src/benchmark/benchmark.cpp), where  we generate read-modify-write operations for keys drawn from a Zipfian distribution.

**Comment by catherine917** [comment]
Thanks @vsreekanti
