### ISSUE TITLE
Is the Lattice (in Anna) a State-based CRDT?

### ISSUE THREAD

**Issue by authwork** [hydro-project/anna#30]
Hello!
After I read the gossip sync:
```
for (const Key &key : local_changeset) {
      ...
      res = process_get(key, serializers[type]); // read the state of the Key from MapLattice
      prepare_put_tuple(gossip_map[address], key, type, res.first);
      ...
      kZmqUtil->send_string(serialized, &pushers[gossip_pair.first]);
}
```
Since the SetLattice is increment-only, the size of SetLattice grows with more PUT updates, this will greatly increase the overhead of sync.

Is there any optimization ways, e.g. to use Delta state CRDTs? How to apply these optimizations?

**Comment by vsreekanti** [comment]
We currently don't implement these optimizations. You would have to implement a new lattice type to support something like this.
