### ISSUE TITLE
A cluster of Anna Servers

### ISSUE THREAD

**Issue by authwork** [hydro-project/anna#31]
@vsreekanti 
Is there any document about Anna (Cluster Mode), instead of [using docker](https://github.com/hydro-project/cluster)? 
Can I directly change the configuration files to launch a cluster of Anna?
For example, I have two nodes with ips: n1, n2, and I want each key has two replications. What's the configuration files on these two nodes, respectively?

**Comment by vsreekanti** [comment]
Hi @authwork -- it's a little hard to read, but you can find all the information we populate the [config file](https://github.com/hydro-project/anna/blob/master/conf/anna-base.yml) with in [this script](https://github.com/hydro-project/anna/blob/master/dockerfiles/start-anna.sh). If you add that information manually, you should be able to run Anna without using Docker and Kubernetes.

**Comment by authwork** [comment]
@vsreekanti 
Thanks for your help.
