### ISSUE TITLE
Missing Client Docs

### ISSUE THREAD

**Issue by MarcoRoenfeldt** [hydro-project/anna#6]
Hi,

is there any documentation about anna-kv clients (either cpp client or the python client)?

Best Regards

**Comment by MarcoRoenfeldt** [comment]
Hi @vsreekanti, I think I already found a bug in the python client. In the modules  base_client, client and lattices there is an unresolveable import
`from anna.anna_pb2 import`
The module anna_pb2 does not exist.

**Comment by vsreekanti** [comment]
The `anna.anna_pb2` module is a compiled protobuf. We don't include it in the repository to avoid having stale versions of the code around. You can use the `[compile.sh](https://github.com/hydro-project/anna/blob/master/client/python/compile.sh)` script to build just the protobufs or use `setup.py` to install the dependency in your local Python environment with the compile protobufs.
